# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The darkthecross workshop
memo: Any Sufficiently advanced technology is indistinguishable from magic.
email: fanmx@umich.edu
description: >- # this means to ignore newlines until "baseurl:"
  This is the personal website of Mingxiang Fan (AKA darkthecross).
baseurl: "" # the subpath of your site, e.g. /blog
url: "darkthecross.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  darkthecross
linkedin_url: https://www.linkedin.com/in/%E6%98%8E%E7%A5%A5-%E6%A8%8A-44b091b4/
author: Mingxiang Fan
# Build settings
markdown: kramdown
theme:
plugins: []
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
